// src/constants/exercises.ts
import { CognitiveExercise } from './types';

export const EXERCISES: CognitiveExercise[] = [
  {
    id: 'memory_match',
    title: 'Memory Match',
    description: 'Flip cards and find matching pairs. Trains short-term visual memory.',
    type: 'memory',
    difficulty: 'easy',
    durationMinutes: 5,
    points: 50,
    icon: '🃏',
  },
  {
    id: 'number_sequence',
    title: 'Number Sequence',
    description: 'Remember and repeat number sequences. Builds working memory.',
    type: 'sequencing',
    difficulty: 'medium',
    durationMinutes: 3,
    points: 60,
    icon: '🔢',
  },
  {
    id: 'word_recall',
    title: 'Word Recall',
    description: 'Study a list of words then recall them from memory.',
    type: 'memory',
    difficulty: 'medium',
    durationMinutes: 5,
    points: 70,
    icon: '📝',
  },
  {
    id: 'pattern_recognition',
    title: 'Pattern Recognition',
    description: 'Identify which shape comes next in the pattern.',
    type: 'pattern',
    difficulty: 'easy',
    durationMinutes: 4,
    points: 55,
    icon: '🔷',
  },
  {
    id: 'colour_word',
    title: 'Colour Word Challenge',
    description: 'Name the colour of the text, not the word it spells. Trains attention.',
    type: 'attention',
    difficulty: 'hard',
    durationMinutes: 3,
    points: 80,
    icon: '🌈',
  },
  {
    id: 'math_mental',
    title: 'Mental Maths',
    description: 'Quick mental arithmetic exercises for cognitive sharpness.',
    type: 'math',
    difficulty: 'medium',
    durationMinutes: 5,
    points: 65,
    icon: '➕',
  },
  {
    id: 'word_association',
    title: 'Word Association',
    description: 'Find words that relate to a given category. Builds language fluency.',
    type: 'language',
    difficulty: 'easy',
    durationMinutes: 4,
    points: 50,
    icon: '💬',
  },
  {
    id: 'spatial_rotation',
    title: 'Spatial Rotation',
    description: 'Identify the rotated version of a shape. Trains spatial awareness.',
    type: 'pattern',
    difficulty: 'hard',
    durationMinutes: 6,
    points: 90,
    icon: '🔄',
  },
];

export const CATEGORY_INFO = {
  medication: { label: 'Medication', icon: '💊', color: '#FF6584' },
  appointment: { label: 'Appointment', icon: '🏥', color: '#6C63FF' },
  exercise: { label: 'Exercise', icon: '🏃', color: '#43D9B0' },
  meal: { label: 'Meal', icon: '🍽️', color: '#FFB347' },
  hygiene: { label: 'Hygiene', icon: '🚿', color: '#4CB8FF' },
  social: { label: 'Social', icon: '👥', color: '#FF8C69' },
  therapy: { label: 'Therapy', icon: '🧠', color: '#9B59B6' },
  other: { label: 'Other', icon: '📌', color: '#95A5A6' },
};

export const MOOD_LABELS: Record<number, { label: string; emoji: string; color: string }> = {
  1: { label: 'Very Low', emoji: '😔', color: '#FF5252' },
  2: { label: 'Low', emoji: '😕', color: '#FFB347' },
  3: { label: 'Neutral', emoji: '😐', color: '#95A5A6' },
  4: { label: 'Good', emoji: '😊', color: '#43D9B0' },
  5: { label: 'Excellent', emoji: '😄', color: '#4CAF50' },
};
